namespace: learnittwice
environments:
  - development
  - staging
  - production
dir:
  app: app
  controllers: app/controllers
  domain: app/domain
  const: app/domain/const
  helpers: app/helpers
  init: app/init
  middlewares: app/middlewares
  models: app/models
  modelsMongo: app/modelsMongo
  modelsMongoNested: app/modelsMongo/nestedSchemas
  logs: logs
  console: console
  databaseQueries: databaseQueries
  backup:
    db:
      mongo: backup/mongo
  entryPoint:
    api:
      controller: app/controllers/api
file:
  app: app/app
  const:
    env: app/domain/const/Env
    language: app/domain/const/Language
    mediaType: app/domain/const/MediaType
    viewTemplate: app/domain/const/ViewTemplate
    wordform: app/domain/const/Wordform
    httpStatusCode: app/domain/const/HttpStatusCode
    studyItemComponentType: app/domain/const/StudyItemComponentType
  console:
    common:
      ArgumentsParser: console/common/
  domain:
    database: app/domain/Database
    databaseMongo: app/domain/DatabaseMongo
    expressApp: app/domain/ExpressApp
  init:
    middleware: app/init/MiddlewareInitializer
    database: app/init/DatabaseInitializer
    databaseMongo: app/init/DatabaseMongoInitializer
    service: app/init/ServiceInitializer
    express: app/init/ExpressInitializer
  modelsMongo:
    nestedSchemas:
      infoSchema: app/modelsMongo/nestedSchemas/InfoSchema
      inboxStudyItemSchema: app/modelsMongo/nestedSchemas/inboxStudyItemSchema
      senseSchema: app/modelsMongo/nestedSchemas/SenseSchema
      studyItemComponentSchema: app/modelsMongo/nestedSchemas/StudyItemComponentSchema
      studyItemSchema: app/modelsMongo/nestedSchemas/StudyItemSchema
      lessonSchema: app/modelsMongo/nestedSchemas/LessonSchema
  postQueries: app/domain/databaseQueries/postQueries.sql,
  db:
    mongo:
      populate: app/db/mongo/populate
  log:
    db: logs/db.log
    error: logs/error.log
  helpers:
    util: app/helpers/Util/index
    timer: app/helpers/Timer
    responsePromise: app/helpers/ResponsePromise
    requestWrapper: app/helpers/RequestWrapper
  entryPoint:
    api:
      entryController: app/controllers/api/_default
db:
  isEnabledLogging: true,
  isEnabledConsoleLoggin: true
entryPoints:
  api:
    routeRoot: /
    # deprecated, in use
    dir:
      controller: /app/controllers/api
    # deperecated, in use
    file:
      entryController: /app/controllers/api/_default
    alias: api
    port: 8081
    protocol: http
    allowedHosts:
      - protocol: http
        host: localhost
        port: 8080