environments:
  - development
  - staging
  - production
dir:
  app: /app
  controllers: /app/controllers
  domain: /app/domain
  helpers: /app/helpers
  init: /app/init
  models: /app/models
  services: /app/services
  logs: /logs
  console: /console
  databaseQueries: /databaseQueries
file:
  app: /app/app
  const:
   language: /app/domain/const/Language
   mediaType: /app/domain/const/MediaType
   viewTemplate: /app/domain/const/ViewTemplate
  domain:
    database: /app/domain/Database
    expressApp: /app/domain/ExpressApp
  init:
    database: /app/init/DatabaseInitializer
    service: /app/init/ServiceInitializer
    express: /app/init/ExpressInitializer
  postQueries: /app/domain/databaseQueries/postQueries.sql
  log:
    db: /logs/db.log
    error: /logs/error.log
  util: /app/helpers/Util
db:
  isEnabledLogging: true,
  isEnabledConsoleLoggin: true
entryPoints:
  api:
    routeRoot: /
    dir:
      controller: /app/controllers/api
    file:
      entryController: /app/controllers/api/_default
    hasView: false    # deprecated
    hasService: true  # deprecated
    alias: api
    port: 8081
    protocol: http