database:
  name: learnittwicev1
  username: root
  password: root
  settings:
    host: 127.0.0.1
    port: 3306
    dialect: mysql
    pool:
      min: 0
      max: 20
      idle: 10000
database_mongo:
  uri: "mongodb://127.0.0.1:27017/learnittwicev2"
  name: "learnittwicev2"
  options:
    user: null
    password: null,
    server:
      poolSize: 400
connection:
  server:
    domain: localhost
    port: 8080
  api_server:
    domain: localhost
    port: 8081